config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :product_name_parsing do
    collection do
      get "tag/:tag", to: "product_name_parsing#tag"
      get "refresh_ingredient_tags", to: "product_name_parsing#refresh_ingredient_tags"
    end
  end
  resources :pack_size_parsing
  resources :brand_parsing do
    collection do
      get "search"
    end
  end
  resources :ingredient

  namespace :api do
    namespace :v1 do
      post 'interpret_pack_size' => 'pack_size#interpret'
    end
  end
end

app/controllers/product_name_parsing_controller.rb
class ProductNameParsingController < ApplicationController

  def index
    @tag_counts = ProductTag.all.map{|t| {tag: t, count: 0}}
    IngredientName.all.includes(:product_tags).each do |ingredient|
      ingredient.product_tags.each do |tag|
        tag_count = @tag_counts.find{|c| c[:tag].name == tag.name}
        tag_count[:count] = tag_count[:count] + 1
      end
    end
    @tag_counts.sort_by{|a| a[:tag].product_tag_group.name}
    render
  end

  def tag
    @names = IngredientName.with_tag(params[:tag]).includes(:product_tags)
    render "tag"
  end

  def refresh_ingredient ingredient, tags, aliases
    parts = ingredient.name.downcase.split(/[. ,]/).reject { |s| s.blank? }
    unused_parts = parts.dup
    parts.each do |part|
      tag_name = aliases.find{|a| a.alias.downcase == part}&.product_tag&.name&.downcase || part
      tag = tags.select{|t| t.name.downcase == tag_name }.first
      if tag.present? && !ingredient.product_tags.where(id: tag.id).any?
        ingredient.product_tags << tag
        unused_parts.reject!{|s| s == part}
      end
    end
    ingredient.tagless_name = unused_parts.join(' ')
    ingredient.save!
  end

  def refresh_ingredient_tags
    tags = ProductTag.all.to_a
    aliases = ProductTagAlias.all.to_a

    IngredientNamesProductTag.delete_all
    IngredientName.includes(:product_tags).all.each do |ingredient|
      refresh_ingredient(ingredient, tags, aliases)
    end

    NutritionalSourceNamesProductTag.delete_all
    NutritionalSourceName.includes(:product_tags).all.each do |ingredient|
      refresh_ingredient(ingredient, tags, aliases)
    end

    ProductNamesProductTag.delete_all
    ProductName.includes(:product_tags).all.each do |ingredient|
      refresh_ingredient(ingredient, tags, aliases)
    end

    render :inline => "<h1>Done</h1>"
  end
end

app/views/product_name_parsing/index.html.haml
%h1 Tags
%br
%br
-#%b Search
-#=form_tag(search_brand_parsing_index_path, :method => :get) do
-#  =text_field_tag :search, params["search"]
-#  =button_tag 'Go', class: 'search-button' , type: :submit
-#%br
-#%br


%table
  %tr{:style=>"text-align:left;"}
    %th{:style=>"padding-right:20px"} Tag Group
    %th Tag
    %th Count
  %tr{:style=>"height:20px"}
  -prev_group = ''
  - @tag_counts.each do |count|
    -show_group = prev_group != count[:tag].product_tag_group.name
    -prev_group = count[:tag].product_tag_group.name
    %tr
      %td{:style=>"border-bottom: 1px grey solid; vertical-align:top; padding-right:20px"}
        -if show_group
          =count[:tag].product_tag_group.name
      %td{:style=>"border-bottom: 1px grey solid; vertical-align:top; padding-right:20px"}
        =link_to count[:tag].name, '/product_name_parsing/tag/' + count[:tag].name
      %td{:style=>"border-bottom: 1px grey solid; vertical-align:top"}= count[:count]

app/views/product_name_parsing/tag.html.haml
%h1= params[:tag]

%table
  %tr{:style=>"height:20px"}
  - @names.each do |name|
    %tr{:style=>"height:30px"}
      %td{:style=>"border-bottom: 1px grey solid; vertical-align:middle"}
        %a{href: '/ingredient/' + name.id.to_s}=name.name
      %td{:style=>"display:inline; vertical-align:middle"}
        - name.product_tags.each do |tag|
          %a.tag{href: '/product_name_parsing/tag/' + tag.name}=tag.name